version: "3.6"

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: broker-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
    # error in course, not supported in newer compose versions
    # deploy:
      # mode: replicated
      # replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: authentication-service.Dockerfile
    restart: always
    ports:
      - "8081:80"
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    # deploy:
    #   mode: replicated
    #   replicas: 1

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ./dbdata/postgres/:/var/lib/postgresql/data/
    # deploy:
    #   mode: replicated
    #   replicas: 1
