version: "3.6"

services:

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ./dbdata/postgres/:/var/lib/postgresql/data/