version: '3'

services:

  caddy:
    image: maxkaemmerer/caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  frontend:
    image: maxkaemmerer/frontend:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: http://backend

  broker-service:
    image: maxkaemmerer/broker-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: maxkaemmerer/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    image: maxkaemmerer/logger-service:1.0.1
    deploy:
      mode: replicated
      replicas: 2

  authentication-service:
    image: maxkaemmerer/auth-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  mailer-service:
    image: maxkaemmerer/mail-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_PORT: 1025
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_USERNAME: user
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: none
      MAIL_FROM_NAME: Mailer
      MAIL_FROM_ADDRESS: noreply@example.com

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    deploy:
      mode: global
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ./dbdata/postgres/:/var/lib/postgresql/data/

  mongo:
    image: "mongo:4.2.16-bionic"
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./dbdata/mongo/:/data/db

  mailhog:
    image: "mailhog/mailhog:latest"
    deploy:
      mode: global
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    deploy:
      mode: global
    ports:
      - "5672:5672"

volumes:
  caddy_data:
  caddy_config: